2025-09-25 08:25:27,281 [INFO] - ============================================================
2025-09-25 08:25:27,281 [INFO] - INICIANDO NOVA EXECUÇÃO DA RPA
2025-09-25 08:25:27,281 [INFO] - ============================================================
2025-09-25 08:25:27,495 [INFO] - FASE 1: LOGIN E CONFIGURAÇÃO DA SESSÃO
2025-09-25 08:25:41,510 [INFO] - 
FASE 2: EXTRAÇÃO DE NOVAS NOTIFICAÇÕES E REGISTRO DE CIÊNCIA
2025-09-25 08:25:41,510 [INFO] - Iniciando módulo de extração e ciência...
2025-09-25 08:25:41,511 [INFO] - Navegando para a Central de Notificações...
2025-09-25 08:25:42,809 [INFO] - Acessando a 'Visão do Advogado'...
2025-09-25 08:25:44,016 [INFO] - --- Processando tarefa: Andamento de publicação em processo de condução terceirizada ---
2025-09-25 08:25:44,047 [INFO] - 79 itens encontrados. Abrindo detalhes...
2025-09-25 08:25:44,890 [INFO] -     - Verificando página 1...
2025-09-25 08:25:47,521 [INFO] -     - Confirmando a ciência...
2025-09-25 08:26:17,525 [ERROR] - Falha ao processar a tarefa 'Andamento de publicação em processo de condução terceirizada': Locator.click: Timeout 30000ms exceeded.
Call log:
  - waiting for get_by_role("button", name="Confirmar")
Traceback (most recent call last):
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/modulo_notificacoes.py", line 75, in extrair_dados_e_dar_ciencia_em_lote
    page.get_by_role("button", name="Confirmar").click()
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 15543, in click
    self._sync(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 549, in click
    await self._channel.send("click", self._timeout, locals_to_params(locals()))
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 69, in send
    return await self._connection.wrap_api_call(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 558, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.click: Timeout 30000ms exceeded.
Call log:
  - waiting for get_by_role("button", name="Confirmar")

2025-09-25 08:26:17,733 [CRITICAL] - Falha irrecuperável na navegação da FASE 2: Page.goto: net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html
Call log:
  - navigating to "https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html", waiting until "load"
Traceback (most recent call last):
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/modulo_notificacoes.py", line 111, in executar_extracao_e_ciencia
    notificacoes, ciencias = extrair_dados_e_dar_ciencia_em_lote(page, tarefa)
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/modulo_notificacoes.py", line 85, in extrair_dados_e_dar_ciencia_em_lote
    page.goto("https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html")
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9019, in goto
    self._sync(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_page.py", line 556, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 153, in goto
    await self._channel.send(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 69, in send
    return await self._connection.wrap_api_call(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 558, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html
Call log:
  - navigating to "https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html", waiting until "load"

2025-09-25 08:26:17,734 [CRITICAL] - Ocorreu uma falha inesperada na automação.
Traceback (most recent call last):
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/main.py", line 52, in main
    stats_extracao = executar_extracao_e_ciencia(page)
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/modulo_notificacoes.py", line 111, in executar_extracao_e_ciencia
    notificacoes, ciencias = extrair_dados_e_dar_ciencia_em_lote(page, tarefa)
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/modulo_notificacoes.py", line 85, in extrair_dados_e_dar_ciencia_em_lote
    page.goto("https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html")
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 9019, in goto
    self._sync(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_page.py", line 556, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 153, in goto
    await self._channel.send(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 69, in send
    return await self._connection.wrap_api_call(
  File "/Users/rildonpimentelpereira/GitHub/OneNotify/venv/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 558, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html
Call log:
  - navigating to "https://juridico.bb.com.br/paj/app/paj-central-notificacoes/spas/central-notificacoes/visao-advogado.app.html", waiting until "load"

2025-09-25 08:26:17,735 [INFO] - Finalizando a automação e fechando o navegador.
2025-09-25 08:26:17,738 [INFO] - 
============================================================
RESUMO FINAL DA EXECUÇÃO (25/09/2025 08:26:17)
============================================================
- Duração Total: 50.24 segundos
- Notificações Salvas: 0
- NPJs com Sucesso: 0
- NPJs com Falha: 0
============================================================

